'use strict';
const $=s=>document.querySelector(s);
const paths={building:'M3 21h18M5 21V7l7-4 7 4v14M9 10h1m4 0h1M9 14h1m4 0h1M10 21v-3h4v3',people:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 3a4 4 0 0 1 0 8M22 21v-2a4 4 0 0 0-3-3.87M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',phone:'M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.96.36 1.9.69 2.79a2 2 0 0 1-.45 2.11L8.09 9.89a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.89.33 1.83.57 2.79.69A2 2 0 0 1 22 16.92z',map:'m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6m6-3v15m6-12v15',check:'M9 11l3 3L22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11',search:'m21 21-4.35-4.35M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',list:'M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01',mail:'M4 4h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2zm-2 2 10 7L22 6'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.building}"/></svg>`;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFKD').replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).toLowerCase();
const sections={entities:{name:'دليل الجهات',title:'كل الجهات، في متناولك.',desc:'ابحث عن جهة، مسؤول، رقم هاتف أو بريد إلكتروني.',icon:'building'},leaders:{name:'القيادة والبروتوكول',title:'المسمى الصحيح، لكل مخاطبة.',desc:'الأسماء والألقاب والمناصب والملاحظات البروتوكولية كما وردت في الملف.',icon:'people'},quick:{name:'الاتصالات السريعة',title:'اتصالاتك الأكثر أهمية.',desc:'مختارات من الجهات ذات الأولوية والخدمات الحيوية.',icon:'phone'},municipalities:{name:'البلديات',title:'مدن الشارقة ومناطقها.',desc:'المديرون وقنوات الاتصال والجهات المرجعية للبلديات.',icon:'map'},maintenance:{name:'التحقق والصيانة',title:'بيانات تستحق المراجعة.',desc:'منهجية التحقق ودورية مراجعة الأسماء والأرقام.',icon:'check'}};
const records=DATA.records.map(r=>{const f=r.fields;return {...r,name:f['الجهة']||f['الاسم الرسمي']||f['المدينة / البلدية']||f['البند'],category:f['التصنيف']||f['الفئة']||'',priority:f['الأولوية']||'',person:f['الرئيس / المسؤول الأعلى']||f['المدير العام / التنفيذي']||f['الصفة / المنصب']||f['المدير']||f['جهة/إدارة الاتصال']||f['الوصف']||'',phone:f['الهاتف العام']||f['الهاتف']||'',email:f['البريد العام']||f['البريد']||'',status:f['حالة التحقق']||f['الحالة']||'',search:norm(Object.values(f).join(' '))};});
let section='entities',view='cards',lastFocus=null,toastTimer;
const review=r=>/يحتاج|تحتاج|غير مثبت|اعتماد أحدث|غير محسوم/.test(r.status);
const phoneParts=r=>String(r.phone).split(/\s*[\/،;؛\n]\s*/).map(x=>x.trim()).filter(x=>/^[+\d\s()\-]+$/.test(x)&&x.replace(/\D/g,'').length>=3);
const tel=p=>{let n=p.replace(/[^+\d]/g,'');return n.startsWith('0')?'+971'+n.slice(1):n;};
const urlLink=u=>{try{const a=new URL(u);return ['https:','http:'].includes(a.protocol)?a.href:null;}catch{return null;}};
function renderNav(){ $('#navigation').innerHTML=Object.entries(sections).map(([k,s])=>`<button class="nav-item ${section===k?'active':''}" data-section="${k}" ${section===k?'aria-current="page"':''}>${icon(s.icon)}<span>${s.name}</span><b>${records.filter(r=>r.kind===k).length}</b></button>`).join(''); }
function resetFilters(){['search','priority','status','category'].forEach(id=>$('#'+id).value='');}
function switchSection(s){section=s;resetFilters();$('#category').innerHTML='<option value="">جميع التصنيفات</option>'+[...new Set(records.filter(r=>r.kind===s).map(r=>r.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')).map(c=>`<option>${esc(c)}</option>`).join('');$('#category').disabled=s!=='entities'&&s!=='leaders';$('#priority').disabled=['municipalities','maintenance'].includes(s);renderNav();render();}
function filtered(){let q=norm($('#search').value.trim()),tokens=q.split(/\s+/).filter(Boolean);let rows=records.filter(r=>(q&&$('#global').checked?r.kind!=='maintenance'||section==='maintenance':r.kind===section));rows=rows.filter(r=>tokens.every(t=>r.search.includes(t)||(/^[\d+\s-]+$/.test(q)&&norm(r.phone).replace(/[^\d]/g,'').includes(q.replace(/[^\d]/g,'')))));let cat=$('#category').value,pr=$('#priority').value,st=$('#status').value;return rows.filter(r=>(!cat||r.category===cat)&&(!pr||r.priority===pr)&&(!st||(st==='review'?review(r):st==='verified'?r.fields['التحقق من الهاتف']==='مطابق لرقم منشور في مصدر رسمي':st==='phone'?phoneParts(r).length:!!r.email)));}
function render(){const s=sections[section],rows=filtered(),all=$('#search').value.trim()&&$('#global').checked;$('#pageTitle').textContent=s.title;$('#pageDescription').textContent=s.desc;$('#breadcrumb').textContent=s.name;$('#resultTitle').textContent=all?'نتائج البحث في الدليل':s.name;$('#count').textContent=rows.length+' نتيجة';$('#results').className='cards '+(view==='list'?'list':'');const n=$('#notice');n.hidden=section!=='leaders'&&$('#status').value!=='review';n.textContent=section==='leaders'?'يُستخدم المسمى الرسمي كاملاً. الأولويات تنظيم داخلي للعمل وليست ترتيباً تشريفياً قانونياً.':'تشمل النتائج أرقاماً لم تُحسم، وأرقاماً من مصادر سابقة، وبيانات وردت عليها ملاحظات في الملف. راجع تفاصيل التحقق ومصدره قبل الاستخدام.';
$('#results').innerHTML=rows.length?rows.map(r=>{const p=phoneParts(r)[0];return `<article class="card"><button class="card-main" data-detail="${r.id}" aria-label="عرض تفاصيل ${esc(r.name)}"><div class="card-top"><span class="entity-icon">${icon(sections[r.kind].icon)}</span>${r.priority?`<span class="tag priority ${['P0','P1'].includes(r.priority)?'urgent':''}">${r.priority}</span>`:''}${review(r)?'<span class="tag review">تحتاج مراجعة</span>':''}</div><span class="category-label">${esc(all?sections[r.kind].name+' · '+r.category:r.category||sections[r.kind].name)}</span><h3>${esc(r.name)}</h3><p class="person">${esc(r.person||'لم يرد اسم المسؤول في الملف')}</p></button><div class="card-bottom">${p?`<a href="tel:${esc(tel(p))}" aria-label="اتصال ${esc(p)}">${icon('phone')}<bdi>${esc(p)}</bdi></a>`:r.kind==='leaders'?'<span class="missing">مرجع للمخاطبات الرسمية</span>':r.kind==='maintenance'?`<span class="missing">${esc(r.fields['التكرار المقترح'])}</span>`:`<span class="missing">${esc(r.phone||'رقم الهاتف غير متاح في الملف')}</span>`}<button class="more" data-detail="${r.id}">التفاصيل</button></div></article>`;}).join(''):'<div class="empty">'+icon('search')+'<h3>لا توجد نتائج مطابقة</h3><p>جرّب كلمة أقصر أو ابحث في جميع الأقسام.</p><button class="action" data-action="reset">مسح البحث والفلاتر</button></div>';}
function richValue(key,value){if(value===null||value==='')return '<span class="missing">غير متاح في الملف</span>';let text=String(value);if(/المصدر|الموقع|مصدر/.test(key)){return text.split(/(https?:\/\/[^\s]+)/g).map(t=>{const u=urlLink(t);return u?`<a class="source-url" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`:esc(t);}).join('');}if(/البريد/.test(key)&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text))return `<a href="mailto:${esc(text)}"><bdi>${esc(text)}</bdi></a>`;if(/الهاتف/.test(key)&&phoneParts({phone:text}).length)return text.split(/(\+?\d[\d ()-]{2,}\d|\b\d{3}\b)/g).map(p=>/^[+\d\s()\-]+$/.test(p)?`<a href="tel:${esc(tel(p))}"><bdi>${esc(p)}</bdi></a>`:esc(p)).join('');return esc(text);}
function displayFields(r){const entries=Object.entries(r.fields);if(r.kind!=='entities'||r.fields['الرئيس / المسؤول الأعلى']||!r.fields['المدير العام / التنفيذي'])return entries;const leadership=['المدير العام / التنفيذي','الرئيس / المسؤول الأعلى','المسمى الرسمي'];const base=entries.filter(([k])=>!leadership.includes(k));const at=base.findIndex(([k])=>k==='الجهة')+1;base.splice(at,0,...leadership.map(k=>[k,r.fields[k]]));return base;}
function openDetail(id){const r=records.find(r=>r.id===id);if(!r)return;$('#detailKind').textContent=sections[r.kind].name+' / '+(r.priority||'البيانات المرجعية');let ps=phoneParts(r);$('#detailBody').innerHTML=`<h2>${esc(r.name)}</h2><p class="detail-sub">${esc(r.person)}</p>${review(r)?`<div class="notice">${esc(r.status)}</div>`:''}<div class="detail-actions"><button class="action primary" data-copy="${r.id}">${r.kind==='leaders'?'نسخ الاسم والمنصب':'نسخ بيانات الاتصال'}</button>${ps.map(p=>`<a class="action" href="tel:${esc(tel(p))}">${icon('phone')}<bdi>${esc(p)}</bdi></a>`).join('')}${r.email?`<a class="action" href="mailto:${esc(r.email)}">${icon('mail')} إرسال بريد</a>`:''}</div><dl class="detail-fields">${displayFields(r).map(([k,v])=>`<div class="field"><dt>${esc(k)}</dt><dd>${richValue(k,v)}</dd></div>`).join('')}</dl><p class="detail-sub" style="margin-top:20px;font-size:12px">المصدر: ورقة «${esc(r.sheet)}» في الملف المرفق. مراجعة الهواتف بتاريخ 8 أكتوبر 2026 موضحة في حقول مستقلة مع المصدر. لا تعني المراجعة إجراء اتصال تجريبي.</p>`;showDialog();}
function showDialog(){lastFocus=document.activeElement;$('#detail').showModal();$('#detail').scrollTop=0;$('#closeDetail').focus();}
function closeDialog(){$('#detail').close();lastFocus?.focus();}
function showGuide(){ $('#detailKind').textContent='حول الدليل';$('#detailBody').innerHTML='<h2>الاستخدام والمصادر</h2><div class="notice">تمت مراجعة 74 جهة: 50 رقماً مطابقاً لمصدر رسمي، و8 من مصادر رسمية سابقة تحتاج تأكيداً حديثاً، و16 غير محسومة. استُكملت أسماء 3 مسؤولين. المؤشرات في جداول الملف الأصلي أدناه تاريخية.</div><p class="detail-sub">محتويات الملف محفوظة في أقسام الدليل. بيانات هذه النسخة بتاريخ 8 أكتوبر 2026.</p>'+['الواجهة','Export Summary'].map(k=>`<h2 class="section-heading">${k==='الواجهة'?'إرشادات ومؤشرات الملف':'معلومات تصدير الملف الأصلي'}</h2><div class="raw-table"><table><tbody>${DATA.raw[k].map(row=>`<tr>${row.filter(v=>v!==null).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`).join('')+'<h2 class="section-heading">الهوية البصرية</h2><p class="detail-sub">استُخدم خط Alexandria الموجود في الموقع الرسمي للمكتب الإعلامي، مع واجهة مستقلة لتنظيم بيانات الملف.</p><a class="action" href="https://sgmb.ae/ar" target="_blank" rel="noopener noreferrer">الموقع المرجعي ↗</a>';showDialog();}
async function copyRecord(id){let r=records.find(r=>r.id===id);const t=r.kind==='leaders'?r.name+'\n'+r.fields['الصفة / المنصب']:Object.entries(r.fields).filter(([k,v])=>v!==null&&v!=='').map(([k,v])=>k+': '+v).join('\n');try{await navigator.clipboard.writeText(t);toast('تم نسخ البيانات');}catch{const area=document.createElement('textarea');area.value=t;$('#detailBody').append(area);area.select();const ok=document.execCommand('copy');area.remove();toast(ok?'تم نسخ البيانات':'تعذر النسخ التلقائي؛ حدد النص وانسخه يدوياً');}}
function toast(t){clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
document.addEventListener('click',e=>{const s=e.target.closest('[data-section]');if(s)switchSection(s.dataset.section);const d=e.target.closest('[data-detail]');if(d)openDetail(d.dataset.detail);const c=e.target.closest('[data-copy]');if(c)copyRecord(c.dataset.copy);const a=e.target.closest('[data-action]');if(a?.dataset.action==='reset'){resetFilters();render();}if(a?.dataset.action==='review'){switchSection('entities');$('#status').value='review';render();}});
$('#search').addEventListener('input',render);['category','priority','status','global'].forEach(id=>$('#'+id).addEventListener('change',render));$('#reset').onclick=()=>{resetFilters();render();};$('#guideBtn').onclick=showGuide;$('#closeDetail').onclick=closeDialog;$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});$('#detail').addEventListener('close',()=>lastFocus?.focus());$('.brand').onclick=e=>{e.preventDefault();switchSection('entities');};
for(const v of ['cards','list'])$('#'+v+'View').onclick=()=>{view=v;for(const x of ['cards','list']){$('#'+x+'View').classList.toggle('active',x===v);$('#'+x+'View').setAttribute('aria-pressed',x===v);}render();};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&!$('#detail').open){e.preventDefault();$('#search').focus();}});
$('#reviewCount').textContent=records.filter(r=>r.kind==='entities'&&review(r)).length;$('#searchIcon').innerHTML=icon('search');$('#cardsView').innerHTML=icon('grid');$('#listView').innerHTML=icon('list');switchSection('entities');
